name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - version.py

jobs:
  Get-Version:
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.version.outputs.app_version }}
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: APP Version
        id: version
        run: |
          APP_VERSION=$(cat version.py | sed -ne 's/APP_VERSION\s=\s"v\(.*\)"/\1/gp')
          echo "检测到版本号为 $APP_VERSION"
          echo "app_version=$APP_VERSION" >> "$GITHUB_OUTPUT"

  Release-Docker-Builder:
    name: Build Docker Image
    needs: [ Get-Version ]
    uses: ./.github/workflows/docker-builder.yaml
    with:
      APP_VERSION: ${{ needs.Get-Version.outputs.app_version }}
      IS_LATEST: true
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
